name: Build Linux x64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
    - name: Prep dir
      run: |
        mkdir build
        cd build
    - name: qmake
      run: |
        pwd
        qmake ..
    - name: make
      run: make -j4
