name: Build Linux x64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      run: | 
        sudo apt-get update
        sudo apt-get install -y qt5-qmake qtbase5-dev libqt5serialport5-dev qtmultimedia5-dev
    - name: qmake
      run: |
        mkdir build
        cd build
        pwd
        qmake ..
        make -j4
